name: Python SDK Test workflow

on:
  push:
    branches:
      - feature/pruebas_ListadoEventos
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "The full commit id to build"
        required: true

jobs:
  comment-run:
    runs-on: ubuntu-latest
    name: Pytest Appium Repo - Android Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -zxvf allure-2.21.0.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # Cambiar a la carpeta android y crear allure-results
      - name: Create allure-results directory inside android
        run: |
          cd android
          mkdir -p allure-results

      # Ejecutar todas las pruebas en Android
      - name: Run all tests in parallel on Android
        run: |
          cd android
          browserstack-sdk pytest -s tes_ubicacion.py --alluredir=allure-results

      # Generar el reporte Allure en HTML
      - name: Generate Allure Report
        run: |
          allure generate android/allure-results --clean -o allure-report

      # Subir el contenido del reporte a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
