name: Python SDK Test workflow

on:
  push:
    branches:
      - feature/pruebas_ListadoEventos
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "The full commit id to build"
        required: true

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    name: Setup Python and Dependencies
    outputs:
      allure-bin-path: ${{ steps.allure-path.outputs.allure-bin-path }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Install browserstack-sdk
        run: python -m pip install browserstack-sdk

      - name: Install Allure
        id: allure-path
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -zxvf allure-2.21.0.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        outputs:
          allure-bin-path: /usr/bin/allure

  test_bstack_sample:
    runs-on: ubuntu-latest
    needs: setup-environment
    name: Run bstack_sample.py test
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd android
          browserstack-sdk pytest -s bstack_sample.py --alluredir=allure-results

  test_coordinadores:
    runs-on: ubuntu-latest
    needs: setup-environment
    name: Run test_coordinadores.py test
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd android
          browserstack-sdk pytest -s test_coordinadores.py --alluredir=allure-results

  test_eventos:
    runs-on: ubuntu-latest
    needs: setup-environment
    name: Run test_eventos.py test
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd android
          browserstack-sdk pytest -s test_eventos.py --alluredir=allure-results

  test_equipo:
    runs-on: ubuntu-latest
    needs: setup-environment
    name: Run tes_equipo.py test
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd android
          browserstack-sdk pytest -s tes_equipo.py --alluredir=allure-results

  test_participantes:
    runs-on: ubuntu-latest
    needs: setup-environment
    name: Run tes_participantes.py test
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd android
          browserstack-sdk pytest -s tes_participantes.py --alluredir=allure-results

  test_ubicacion:
    runs-on: ubuntu-latest
    needs: setup-environment
    name: Run tes_ubicacion.py test
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd android
          browserstack-sdk pytest -s tes_ubicacion.py --alluredir=allure-results

  generate_report:
    runs-on: ubuntu-latest
    needs:
      - test_bstack_sample
      - test_coordinadores
      - test_eventos
      - test_equipo
      - test_participantes
      - test_ubicacion
    name: Generate Allure Report and Deploy to GitHub Pages
    steps:
      - name: Generate Allure Report
        run: |
          allure generate android/allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
